- **1. Introduction to Data and Storage Fundamentals**
  - The Importance of Data in Modern Systems
  - Types of Data (Structured, Unstructured, Semi-Structured)
  - Different Storage Systems (DAS, NAS, SAN, Object Storage)
- **2. Disk Performance Characteristics**
  - IOPS (Input/Output Operations)
  - Latency (Response Time)
  - Throughput (Data Transfer Rate)
  - Comparing Disk Types (HDD, SSD, NVMe) for Performance
- **3. Software-Defined Storage (SDS) and the Role of Networking**
  - Introduction to Software-Defined Storage (SDS)
  - The Importance of Networking in SDS
  - Network Considerations for Performance and Reliability in SDS
- **4. Introduction to Ceph: What It Is and What It Offers**
  - Overview of Ceph as a Distributed Storage System
  - Key Services Provided by Ceph (Block, File, Object Storage)
  - Benefits of Using Ceph in Modern Infrastructure
- **5. Understanding File Systems**
  - What is a File System and Why It Matters
  - Common File Systems (ext4, NTFS, XFS, etc.)
  - Distributed File Systems: An Overview
- **6. How Data is Stored in Ceph**
  - Core Concepts in Ceph Storage
  - Objects, Placement Groups (PGs), and Their Role in Data Safety and Distribution
  - BlueStore, OSDs, and MONs: Building Blocks of Ceph
  - Data Protection Mechanisms in Ceph
- (Continuation of Data Protection Mechanisms in Ceph)
  - Replication
  - Erasure Coding (EC)
- **7. High Availability (HA) in Ceph Components**
  - How Ceph Ensures High Availability for Its Components
  - Redundancy and Failover Mechanisms in Ceph
- **8. Working with Ceph Block Device (RBD)**
  - Creating Ceph Block Device
  - Configuring Ceph Client
  - Mapping Ceph Block Device
  - Resizing Ceph RBD
  - Working with RBD Snapshots
  - Working with RBD Clones
  - Disaster Recovery Replication Using RBD Mirroring
  - Configuring Image Mirroring
  - Recovering from a Disaster
- **9. Working with Ceph File-System (Ceph-FS)**
  - Deploying Ceph MDS
  - Accessing Ceph FS Through Kernel Driver
  - Exporting the Ceph Filesystem as NFS
  - Mount CephFS on Windows (Ceph Dokan)
- **10. Ceph Object Storage and RADOS Gateway (RGW)**
  - Installing and Configuring the RADOS Gateway Node
  - Accessing the Ceph Object Storage Using the S3 Cli
  - Install & Configure s3cmd Tools and S3 Browser
  - Manage User Access and Quota Limit in Object Storage
  - Ceph Object Storage Multi-Site
  - Accessing the Ceph Object Storage Using the Swift

- **11. Ceph Recommendations and Performance Tuning**
  - Overview of Ceph Performance Tuning Strategies
  - Ceph Cache Tiering for Performance Optimization
  - BlueStore Cache: Enhancing Ceph Performance
  - OpenCAS (Caching for Ceph) and Its Benefits
- **12. Integrating Ceph with Platforms (Kubernetes and OpenStack)**
  - Configuring OpenStack Cinder & Glance with Ceph Storage
  - Install & Configure Rook Ceph on Kubernetes
  - Configure Storage Class and Persistence Volume as a RBD on Ceph Cluster
  - Configure Storage Class and Persistence Volume as a Ceph-FS on Ceph Cluster
  - Connect External Ceph Cluster to Kubernetes as a RBD and Ceph-FS
- **13. Monitoring, Dashboard, and Troubleshooting Ceph**
  - Monitoring Ceph Cluster with Prometheus and Grafana
  - Managing Ceph Cluster Logs and Events
  - Using Ceph Dashboard for Cluster Management
  - Troubleshooting and Maintaining Ceph Cluster with Command-Line Tools (OSD Replacement)
  - Checking Cluster Health with Ceph Commands
  - Common Issues and How to Resolve Them
